### ISSUE TITLE
Module dependencies that don't exist prevent task from completing and no message

### ISSUE THREAD

**Issue by apmsooner** [alexweber/environments#1]
First off... this module is awesome but i found something that could be improved i think.
I created a task bundle called "Enable Development Modules" with tasks:
enable
- devel
  -devel_themer
  and Enable dependencies: yes
  I forgot to add the Simplehtmldom module which is a requirement for devel_themer. Dumb on my part however the task completed as if everything was fine however neither module was enabled since that 1 dependency wasn't met. Is there any way to return a message that says the module dependencies weren't met so task failed?

**Comment by alexweber** [comment]
@apmsooner Thanks! :)  Good call, I'm working on improving the dependency resolution for exported environments in features too.  Will fix!

**Comment by alexweber** [comment]
The fix made it into the latest release (1.0-rc4).

Caveat: the task will just display a message and might not necessarily fail.  More on that in another issue...
