### ISSUE TITLE
Variables don't set

### ISSUE THREAD

**Issue by apmsooner** [alexweber/environments#4]
Tried in task bundle as well as just an individual task itself but this doesn't seem to change the value from 0:

Set variable value  
Name: cache
Value type: integer
Value: 1

**Comment by apmsooner** [comment]
I think the issue with this one is i was trying to set a default environment variable in my setting.php file like this:  $conf['environments_env'] = 'live';
It appears the module needs a change event between environments in order for the tasks to run. I'm on pantheon environment so my intent was that when i copied database down from live to test, the environment variable would be set for test to run the tasks i setup for that specific environment.

**Comment by miloskroulik** [comment]
Isn't it best to just set up multiple settings.php files (per environments)?

**Comment by alexweber** [comment]
Hello @apmsooner, I'm sorry I have no clue why i didn't see the notification about this issue.

Yes, you are correct, it needs a change event to trigger the setup at the moment.  I'm working on some update hook integration to smooth the process out.

@miloskroulik If all you want to do is change a few variable values then multiple settings.php per environments is perfect!

**Comment by alexweber** [comment]
Closing this in favor of a dedicated issue for update hook support.
