### ISSUE TITLE
Manage tasks display does not respect task order

### ISSUE THREAD

**Issue by ekubovsky** [alexweber/environments#5]
When using features to store environment and task configurations, the order of tasks is not respected
![image](https://user-images.githubusercontent.com/12180836/177888504-a7b47be6-dad0-4360-a54e-e99541f0fdd7.png)

**Comment by ekubovsky** [comment]
The patch cannot be attached. So see the code below:

```
diff --git a/environments.admin.inc b/environments.admin.inc
--- a/environments.admin.inc
+++ b/environments.admin.inc
@@ -85,7 +85,7 @@
       '#tree' => TRUE,
     );
 
-    foreach (element_children($object->tasks) as $id) {
+    foreach (element_children($object->tasks, TRUE) as $id) {
       $task = $object->tasks[$id];
 
       // Prevent warnings.
```

PS. Same exact solution is used when tasks are executed, not sure why it was not applied to the admin display.

**Comment by alexweber** [comment]
Thx!

**Comment by alexweber** [comment]
Thanks!
